AppBundle\Entity\YjCollectingData:
    type: entity
    table: yj_collecting_data
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        source:
            type: string
            nullable: true
            length: 255
            fixed: false
        fileName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: file_name
        isUse:
            type: boolean
            nullable: true
            default: '0'
            column: is_use
        type:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
        isCut:
            type: boolean
            nullable: true
            default: '0'
            column: is_cut
    lifecycleCallbacks: {  }
