AppBundle\Entity\YjCollectionCategory:
    type: entity
    table: yj_collection_category
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: category_name
        addTime:
            type: integer
            nullable: true
            unsigned: false
            column: add_time
    lifecycleCallbacks: {  }
